__title__ = "TTkiteconnect"
__description__ = "The unofficial Python client for the Kite Connect trading API"
__url__ = "https://kite.trade"
__download_url__ = "https://github.com/debdungeon/pykiteconnect"
__version__ = "3.8.2.1"
__author__ = "Zerodha Technology Pvt ltd. (India)"
__author_email__ = "talk@zerodha.tech"
__license__ = "MIT"
